const messages = [
    "Believe in yourself and you will be unstoppable - Your lucky star is Sirius!",
    "Embrace challenges and let them fuel your growth - Your lucky star is Polaris!",
    "Stay focused on your goals and watch your dreams come true - Your lucky star is Proxima Centauri!",
    "Never underestimate the power of determination - Your lucky star is Betelgeuse!",
    "Success comes to those who persevere - Your lucky star is Rigel!",
    "Every setback is an opportunity for a comeback - Your lucky star is Antares!",
    "Embrace change and let it lead you to greatness - Your lucky star is Arcturus!",
    "Your potential knows no bounds - Your lucky star is Alpha Centauri!",
    "Believe in the beauty of your dreams - Your lucky star is Vega!",
    "Hard work and dedication always pay off - Your lucky star is Canopus!",
    "Don't be afraid to take risks and reach for the stars - Your lucky star is Deneb!",
    "Keep pushing forward even when the going gets tough - Your lucky star is Aldebaran!",
    "Every day is a new chance to make a difference - Your lucky star is Altair!",
    "Success is the sum of small efforts repeated day in and day out - Your lucky star is Spica!",
    "Dream big and let your passion guide you - Your lucky star is Pollux!",
    "You have the power to create your own destiny - Your lucky star is Regulus!",
    "Believe in yourself and nothing will be impossible - Your lucky star is Eta Carinae!",
    "Stay determined, and success will follow - Your lucky star is Capella!",
    "Hardships are stepping stones to resilience - Your lucky star is Alpheratz!",
    "Keep going, even when it feels impossible - Your lucky star is Denebola!",
    "The road to success is paved with hard work and determination - Your lucky star is Alnitak!",
    "Every challenge you face is an opportunity to grow - Your lucky star is Fomalhaut!",
    "Your dreams are within reach, keep striving - Your lucky star is Bellatrix!",
    "Believe in your abilities and you'll be unstoppable - Your lucky star is Castor!",
    "Never give up on what you truly want - Your lucky star is Achernar!",
    "Your perseverance will lead you to greatness - Your lucky star is Alhena!",
    "Chase your dreams with unwavering passion - Your lucky star is Alnair!",
    "In every obstacle lies an opportunity for growth - Your lucky star is Alnilam!",
    "You are capable of achieving amazing things - Your lucky star is Arcturus!",
    "Keep pushing forward, even when it's challenging - Your lucky star is Canopus!",
    "Your dedication will pave the path to success - Your lucky star is Bellatrix!",
    "Never let fear hold you back from reaching your full potential - Your lucky star is Betelgeuse!",
    "Dream big and dare to fail - Your lucky star is Capella!",
    "Believe in yourself and others will believe in you too - Your lucky star is Castor!",
    "Success comes to those who work for it - Your lucky star is Vega!",
    "You have the power to make a difference - Your lucky star is Procyon!",
    "Embrace challenges as opportunities for growth - Your lucky star is Rigel!",
    "Your determination will open doors to success - Your lucky star is Sirius!",
    "Stay focused and success will be yours - Your lucky star is Arcturus!",
    "Your dreams are worth the effort - Your lucky star is Polaris!",
    "Don't be afraid to take the road less traveled - Your lucky star is Altair!",
    "Every step forward brings you closer to your goals - Your lucky star is Aldebaran!",
    "Believe in yourself, and anything is possible - Your lucky star is Antares!",
    "Your hard work will pay off - Your lucky star is Arcturus!",
    "Success begins with a single step - Your lucky star is Canopus!",
    "Stay determined, even in the face of adversity - Your lucky star is Betelgeuse!",
    "Keep striving for greatness - Your lucky star is Vega!",
    "Never lose sight of your dreams - Your lucky star is Proxima Centauri!",
    "You have the power to shape your own destiny - Your lucky star is Polaris!",
    "Dream big and never give up - Your lucky star is Deneb!",
    "Every failure is a stepping stone to success - Your lucky star is Bellatrix!",
    "Stay focused on your goals and believe in yourself - Your lucky star is Castor!",
    "Hard work and determination will lead you to success - Your lucky star is Achernar!",
    "Your perseverance will overcome any obstacle - Your lucky star is Fomalhaut!",
    "Believe in yourself, and the world will believe in you - Your lucky star is Spica!",
    "Success is within your reach - Your lucky star is Pollux!",
    "Embrace challenges and let them fuel your growth - Your lucky star is Alhena!",
    "Your dreams are worth fighting for - Your lucky star is Alnair!",
    "Stay true to yourself and success will follow - Your lucky star is Alnilam!",
    "You are capable of amazing things - Your lucky star is Denebola!",
    "Don't be afraid to chase your dreams - Your lucky star is Alnitak!",
    "Every setback is a setup for a comeback - Your lucky star is Arcturus!",
    "Your determination will light the path to success - Your lucky star is Bellatrix!",
    "Believe in your abilities, and you'll be unstoppable - Your lucky star is Betelgeuse!",
    "Stay focused on your goals and success will follow - Your lucky star is Capella!",
    "Dream big and never stop pursuing your passions - Your lucky star is Castor!",
    "Your perseverance will lead you to greatness - Your lucky star is Vega!",
    "Embrace challenges as opportunities for growth - Your lucky star is Polaris!",
    "Stay determined and overcome any obstacle - Your lucky star is Procyon!",
    "Your dreams are the fuel for your success - Your lucky star is Rigel!",
    "Don't let fear hold you back from achieving greatness - Your lucky star is Sirius!",
    "Every step you take brings you closer to your dreams - Your lucky star is Altair!",
    "Believe in yourself, and the possibilities are endless - Your lucky star is Aldebaran!",
    "Stay true to yourself and follow your passion - Your lucky star is Antares!",
    "Success is the result of hard work and perseverance - Your lucky star is Arcturus!",
    "Your dedication will pave the way to success - Your lucky star is Canopus!",
    "Dream big and let your determination shine - Your lucky star is Bellatrix!",
    "Never give up on your dreams - Your lucky star is Achernar!",
    "You have the power to turn your dreams into reality - Your lucky star is Alhena!",
    "Stay focused on your goals, and success will be yours - Your lucky star is Alnair!",
    "Believe in yourself and trust the journey - Your lucky star is Alnilam!",
    "Every failure is a lesson in disguise - Your lucky star is Arcturus!",
    "Your dreams are worth the effort - Your lucky star is Deneb!",
    "Keep pushing forward, even when faced with challenges - Your lucky star is Fomalhaut!",
    "Success comes to those who never give up - Your lucky star is Spica!",
    "You are capable of achieving greatness - Your lucky star is Pollux!",
    "Embrace challenges as opportunities for growth - Your lucky star is Regulus!",
    "Stay determined and let your dreams guide you - Your lucky star is Eta Carinae!",
    "Believe in yourself, and you'll achieve the extraordinary - Your lucky star is Capella!",
    "Dream big and make it happen - Your lucky star is Alpheratz!",
    "Never let anyone dim your light - Your lucky star is Denebola!",
    "Stay true to yourself and your dreams - Your lucky star is Alnitak!",
    "Your determination will overcome any obstacle - Your lucky star is Aldebaran!",
    "Believe in the power of your dreams - Your lucky star is Altair!",
    "Success is the result of hard work and perseverance - Your lucky star is Alhena!",
    "Your dedication will lead you to success - Your lucky star is Alnair!",
    "Dream big and never give up on yourself - Your lucky star is Alnilam!",
    "Stay focused on your goals and let nothing hold you back - Your lucky star is Arcturus!",
    "You have the power to achieve greatness - Your lucky star is Betelgeuse!",
    "Believe in yourself and let your light shine - Your lucky star is Canopus!",  ]
  
  const stellarMessage = () => {
    const message = messages[Math.floor(Math.random() * messages.length)];
    console.log(`\x1b[34m${message}\x1b[89m`);
  }
  
  module.exports = {
    stellarMessage
  };